// GENERATED by knowledge-base/generate.py in the app repo — do not edit here.
//
// Edit knowledge-base/articles/*.md (and the translations beside them) in the
// app repo, run `python3 knowledge-base/generate.py --next <this site>`, and
// commit the result. Keeping the answers in one place is the whole point: the
// app, this site and the support replies must not drift apart.

export type HelpArticle = {
  id: string;
  title: string;
  summary: string;
  body: string;
};

export type HelpLocale = {
  lang: string;
  dir: "ltr" | "rtl";
  label: string;
  heading: string;
  back: string;
  stillStuck: string;
  articles: HelpArticle[];
};

export const SUPPORT_EMAIL = "support@saudiarabiavpn.app";

export const HELP_LOCALES: Record<string, HelpLocale> = {
  "en": {
    "lang": "en",
    "dir": "ltr",
    "label": "English",
    "heading": "Help",
    "back": "← All topics",
    "stillStuck": "Still stuck? Email us at",
    "articles": [
      {
        "id": "cannot_connect",
        "title": "The app won't connect",
        "summary": "Connection attempts fail or never finish.",
        "body": "Try another server first — a single server can be busy or temporarily down, and switching is faster than any other fix. Open Server location, pick a different country, and connect again. If no server works, turn Wi-Fi off and try mobile data (or the other way round): the problem is usually the network, not the app. Still nothing? Restart your device, then try once more. Most connection failures are caused by the network you are on, which is why changing network or server solves the large majority of them."
      },
      {
        "id": "keeps_dropping",
        "title": "The connection keeps dropping",
        "summary": "You connect successfully, then get disconnected again.",
        "body": "A tunnel that opens and then closes usually means the network underneath it is unstable or is interfering with VPN traffic. Move closer to your router or switch between Wi-Fi and mobile data to rule out signal problems. If it only drops on one network — an office, a school, a hotel — that network is probably filtering VPN traffic, and another server or country often gets through. On Android, also check that the system is not closing the app in the background."
      },
      {
        "id": "wifi_signin",
        "title": "Public Wi-Fi that needs a sign-in",
        "summary": "Cafés, hotels, airports and trains often block everything until you log in.",
        "body": "These networks hold back all traffic until you accept their terms on a sign-in page, and a VPN cannot connect before that happens. Disconnect the VPN, open your browser and load any plain website — the sign-in page should appear. Complete it, confirm normal browsing works, and only then connect the VPN. If no page appears, forget the network on your device and join it again."
      },
      {
        "id": "network_blocks_vpn",
        "title": "Your network blocks VPN connections",
        "summary": "Some offices, schools, hotels and providers deliberately block VPN traffic.",
        "body": "If the app works on mobile data but not on one particular Wi-Fi, that network is blocking VPN traffic on purpose. This is a restriction set by whoever runs the network, not a fault in the app. Try a different server or country — not all of them are blocked in the same way — and try again after switching networks. On a managed network, such as a company or school, the block is often enforced centrally and cannot be worked around from the app."
      },
      {
        "id": "android_battery",
        "title": "Android is closing the app in the background",
        "summary": "Battery saving features can shut down the tunnel when the screen is off.",
        "body": "Android aggressively stops background apps to save power, and that can end a VPN session while you are not looking. Open your device settings, find this app under Apps, and set its battery option to Unrestricted (the wording differs per manufacturer — Samsung, Xiaomi, Huawei and OnePlus each phrase it differently). Also make sure the app is not in any 'sleeping' or 'restricted' list. After changing this, connect again and the session should survive the screen going off."
      },
      {
        "id": "ios_vpn_permission",
        "title": "iPhone asks to allow a VPN configuration",
        "summary": "iOS needs your permission once before any VPN app can connect.",
        "body": "The first time you connect, iOS asks to add a VPN configuration and may ask for your passcode or Face ID. This is a standard iOS prompt and the app cannot connect until you allow it. If you declined it earlier, go to Settings, then General, then VPN & Device Management, remove any old configuration for this app, and connect again to get a fresh prompt. If another VPN app is installed, make sure it is disconnected — only one VPN can be active at a time."
      },
      {
        "id": "device_clock",
        "title": "Your device's date and time are wrong",
        "summary": "A clock that is off by more than a few minutes breaks the secure handshake.",
        "body": "Secure connections check certificates against the current time, so a device whose clock is wrong will fail to connect even on a perfect network. Open your device settings and turn on automatic date and time, then connect again. This one is easy to miss because everything else on the device appears to work normally."
      },
      {
        "id": "slow_speed",
        "title": "The connection is slow",
        "summary": "Speed depends mostly on distance to the server and how busy it is.",
        "body": "A VPN always costs some speed, because your traffic takes a longer path and is encrypted on the way. Pick a server close to you — a nearby country is almost always faster than a distant one. Swipe a server to the left and tap PING to see how quickly it responds, and prefer a low number. Free servers are shared by many people and are busier at peak hours; premium servers carry fewer users. Also test your speed with the VPN off, so you know what your connection can actually do."
      },
      {
        "id": "streaming_blocked",
        "title": "A streaming service won't work",
        "summary": "Large streaming platforms actively detect and block VPNs.",
        "body": "Streaming services are required by their licences to show content per country, so they invest heavily in detecting VPN traffic and blocking it. This affects every VPN, not just this app, and a server that works today may be detected tomorrow. Trying a different server sometimes helps, but no VPN can promise access to a particular streaming service, and we cannot guarantee it."
      },
      {
        "id": "free_time_limit",
        "title": "Your free connection time ran out",
        "summary": "Free servers include a set amount of connection time each day.",
        "body": "Free servers come with a daily allowance of connection time, which resets every day. When it runs out you can watch a short video to extend it, a limited number of times per day. This is how the free version is paid for, and it is working as intended rather than failing. A subscription removes the time limit completely, unlocks every server and removes the ads."
      },
      {
        "id": "subscription_help",
        "title": "Subscriptions, restoring and refunds",
        "summary": "Purchases are handled by the App Store and Google Play, not by us.",
        "body": "If you subscribed and the app still shows the free version, open the subscription screen and tap Restore purchases, making sure you are signed in with the account you bought it on. Subscriptions renew automatically and are cancelled in your store account — on iPhone under your Apple Account subscriptions, on Android under Payments and subscriptions in the Play Store. Refunds are issued by the store, so requests have to go through Apple or Google."
      }
    ]
  },
  "ar": {
    "lang": "ar",
    "dir": "rtl",
    "label": "العربية",
    "heading": "المساعدة",
    "back": "← كل المواضيع",
    "stillStuck": "ما زالت المشكلة قائمة؟ راسلنا على",
    "articles": [
      {
        "id": "cannot_connect",
        "title": "التطبيق لا يتصل",
        "summary": "محاولات الاتصال تفشل أو لا تنتهي أبدًا.",
        "body": "جرّب خادمًا آخر أولًا — قد يكون خادم بعينه مزدحمًا أو متوقفًا مؤقتًا، والتبديل أسرع من أي حل آخر. افتح موقع الخادم، واختر دولة مختلفة، ثم أعد الاتصال. إذا لم يعمل أي خادم، أوقف شبكة Wi-Fi واستخدم بيانات الهاتف (أو العكس): فالمشكلة عادةً في الشبكة وليست في التطبيق. ما زال الأمر كما هو؟ أعد تشغيل جهازك ثم حاول مرة أخرى. معظم حالات فشل الاتصال سببها الشبكة التي تستخدمها، ولهذا فإن تغيير الشبكة أو الخادم يحل الغالبية العظمى منها."
      },
      {
        "id": "keeps_dropping",
        "title": "الاتصال ينقطع باستمرار",
        "summary": "يتم الاتصال بنجاح ثم ينقطع مرة أخرى.",
        "body": "النفق الذي يفتح ثم يُغلق يعني غالبًا أن الشبكة الأساسية غير مستقرة أو أنها تتداخل مع حركة VPN. اقترب من جهاز التوجيه أو بدّل بين Wi-Fi وبيانات الهاتف لاستبعاد مشكلات الإشارة. إذا كان الانقطاع يحدث في شبكة واحدة فقط — مكتب أو مدرسة أو فندق — فالأرجح أن تلك الشبكة تصفّي حركة VPN، وغالبًا ما ينجح خادم أو بلد آخر. على نظام Android، تحقق أيضًا من أن النظام لا يغلق التطبيق في الخلفية."
      },
      {
        "id": "wifi_signin",
        "title": "شبكة Wi-Fi عامة تتطلب تسجيل الدخول",
        "summary": "المقاهي والفنادق والمطارات والقطارات تحجب كل شيء حتى تسجّل الدخول.",
        "body": "تحتجز هذه الشبكات كل حركة البيانات حتى توافق على شروطها في صفحة تسجيل الدخول، ولا يمكن لـ VPN الاتصال قبل ذلك. افصل VPN، وافتح المتصفح، وحمّل أي موقع عادي — ينبغي أن تظهر صفحة تسجيل الدخول. أكمِلها، وتأكد أن التصفح العادي يعمل، وعندها فقط شغّل VPN. إذا لم تظهر أي صفحة، انسَ الشبكة من جهازك ثم انضم إليها من جديد."
      },
      {
        "id": "network_blocks_vpn",
        "title": "شبكتك تحجب اتصالات VPN",
        "summary": "بعض المكاتب والمدارس والفنادق ومزودي الخدمة يحجبون حركة VPN عمدًا.",
        "body": "إذا كان التطبيق يعمل على بيانات الهاتف ولا يعمل على شبكة Wi-Fi معينة، فتلك الشبكة تحجب حركة VPN عن قصد. هذا قيد يضعه من يدير الشبكة، وليس خللًا في التطبيق. جرّب خادمًا أو دولة أخرى — فليست كلها محجوبة بالطريقة نفسها — وأعد المحاولة بعد تغيير الشبكة. في الشبكات المُدارة، كشبكات الشركات أو المدارس، يُطبَّق الحجب مركزيًا في الغالب ولا يمكن تجاوزه من داخل التطبيق."
      },
      {
        "id": "android_battery",
        "title": "نظام Android يغلق التطبيق في الخلفية",
        "summary": "ميزات توفير البطارية قد تنهي النفق عند إطفاء الشاشة.",
        "body": "يغلق Android تطبيقات الخلفية بصرامة لتوفير الطاقة، وقد ينهي ذلك جلسة VPN دون أن تنتبه. افتح إعدادات الجهاز، وابحث عن هذا التطبيق ضمن التطبيقات، واضبط خيار البطارية على «غير مقيّد» (تختلف التسمية حسب الشركة المصنّعة — Samsung وXiaomi وHuawei وOnePlus تستخدم صياغات مختلفة). تأكد أيضًا من أن التطبيق ليس ضمن قوائم التطبيقات «النائمة» أو «المقيّدة». بعد هذا التغيير، أعد الاتصال وينبغي أن تستمر الجلسة بعد إطفاء الشاشة."
      },
      {
        "id": "ios_vpn_permission",
        "title": "iPhone يطلب السماح بإعداد VPN",
        "summary": "يحتاج iOS إلى إذنك مرة واحدة قبل أن يتمكن أي تطبيق VPN من الاتصال.",
        "body": "في أول اتصال، يطلب iOS إضافة إعداد VPN وقد يطلب رمز الدخول أو Face ID. هذا طلب قياسي من iOS ولا يمكن للتطبيق الاتصال قبل السماح به. إذا رفضته سابقًا، انتقل إلى الإعدادات، ثم عام، ثم VPN وإدارة الجهاز، واحذف أي إعداد قديم لهذا التطبيق، ثم أعد الاتصال للحصول على طلب جديد. وإذا كان لديك تطبيق VPN آخر مثبّت، فتأكد من أنه غير متصل — إذ لا يمكن تفعيل أكثر من VPN واحد في الوقت نفسه."
      },
      {
        "id": "device_clock",
        "title": "تاريخ ووقت جهازك غير صحيحين",
        "summary": "الساعة التي تزيد عن بضع دقائق خطأً تُفسد المصافحة الآمنة.",
        "body": "تتحقق الاتصالات الآمنة من الشهادات مقابل الوقت الحالي، لذا فإن جهازًا ساعته خاطئة سيفشل في الاتصال حتى على شبكة مثالية. افتح إعدادات الجهاز، وفعّل ضبط التاريخ والوقت تلقائيًا، ثم أعد الاتصال. يسهل إغفال هذا السبب لأن كل شيء آخر في الجهاز يبدو أنه يعمل بشكل طبيعي."
      },
      {
        "id": "slow_speed",
        "title": "الاتصال بطيء",
        "summary": "تعتمد السرعة أساسًا على بُعد الخادم ومدى ازدحامه.",
        "body": "يكلّف VPN دائمًا بعض السرعة، لأن بياناتك تسلك مسارًا أطول وتُشفَّر في الطريق. اختر خادمًا قريبًا منك — فالدولة القريبة أسرع دائمًا تقريبًا من البعيدة. اسحب الخادم إلى اليسار واضغط PING لترى سرعة استجابته، وفضّل الرقم الأقل. الخوادم المجانية يتشاركها كثيرون وتزداد ازدحامًا في ساعات الذروة، بينما تحمل الخوادم المدفوعة مستخدمين أقل. اختبر سرعتك أيضًا مع إيقاف VPN لتعرف ما يقدّمه اتصالك فعليًا."
      },
      {
        "id": "streaming_blocked",
        "title": "خدمة بث لا تعمل",
        "summary": "منصات البث الكبرى تكتشف شبكات VPN وتحجبها بنشاط.",
        "body": "تُلزم التراخيص خدمات البث بعرض المحتوى حسب الدولة، لذا تستثمر كثيرًا في اكتشاف حركة VPN وحجبها. هذا يؤثر على كل شبكات VPN وليس هذا التطبيق وحده، وقد يُكتشف غدًا خادم يعمل اليوم. تجربة خادم آخر تساعد أحيانًا، لكن لا يمكن لأي VPN أن يَعِد بالوصول إلى خدمة بث بعينها، ولا يمكننا ضمان ذلك."
      },
      {
        "id": "free_time_limit",
        "title": "انتهى وقت الاتصال المجاني",
        "summary": "تتضمن الخوادم المجانية قدرًا محددًا من وقت الاتصال كل يوم.",
        "body": "تأتي الخوادم المجانية بحصة يومية من وقت الاتصال تتجدد كل يوم. وعند نفادها يمكنك مشاهدة مقطع قصير لتمديدها، لعدد محدود من المرات يوميًا. هكذا تموَّل النسخة المجانية، وهذا سلوك مقصود وليس عطلًا. أما الاشتراك فيلغي حد الوقت تمامًا، ويفتح كل الخوادم، ويزيل الإعلانات."
      },
      {
        "id": "subscription_help",
        "title": "الاشتراكات والاستعادة والاسترداد",
        "summary": "تتولى App Store وGoogle Play معالجة عمليات الشراء، لا نحن.",
        "body": "إذا اشتركت وما زال التطبيق يعرض النسخة المجانية، فافتح شاشة الاشتراك واضغط «استعادة المشتريات»، مع التأكد من تسجيل الدخول بالحساب الذي اشتريت به. تتجدد الاشتراكات تلقائيًا وتُلغى من حساب المتجر — على iPhone ضمن اشتراكات حساب Apple، وعلى Android ضمن المدفوعات والاشتراكات في متجر Play. أما الاسترداد فيصدر عن المتجر، لذا يجب توجيه الطلبات إلى Apple أو Google."
      }
    ]
  },
  "bn": {
    "lang": "bn",
    "dir": "ltr",
    "label": "বাংলা",
    "heading": "সহায়তা",
    "back": "← সব বিষয়",
    "stillStuck": "এখনও সমাধান হয়নি? আমাদের ইমেইল করুন",
    "articles": [
      {
        "id": "cannot_connect",
        "title": "অ্যাপটি সংযুক্ত হচ্ছে না",
        "summary": "সংযোগের চেষ্টা ব্যর্থ হয় বা কখনও শেষ হয় না।",
        "body": "প্রথমে অন্য একটি সার্ভার চেষ্টা করুন — একটি নির্দিষ্ট সার্ভার ব্যস্ত বা সাময়িকভাবে বন্ধ থাকতে পারে, আর সার্ভার বদলানো অন্য যেকোনো সমাধানের চেয়ে দ্রুত। সার্ভার লোকেশন খুলুন, অন্য একটি দেশ বেছে নিন এবং আবার সংযোগ করুন। যদি কোনো সার্ভারই কাজ না করে, Wi-Fi বন্ধ করে মোবাইল ডেটা ব্যবহার করুন (বা উল্টোটা): সমস্যা সাধারণত নেটওয়ার্কের, অ্যাপের নয়। তবুও কাজ হচ্ছে না? ডিভাইসটি রিস্টার্ট করে আরেকবার চেষ্টা করুন। অধিকাংশ সংযোগ ব্যর্থতার কারণ আপনি যে নেটওয়ার্কে আছেন সেটিই, তাই নেটওয়ার্ক বা সার্ভার বদলালেই বেশিরভাগ সমস্যার সমাধান হয়ে যায়।"
      },
      {
        "id": "keeps_dropping",
        "title": "সংযোগ বারবার বিচ্ছিন্ন হচ্ছে",
        "summary": "সফলভাবে সংযুক্ত হওয়ার পর আবার সংযোগ কেটে যায়।",
        "body": "যে টানেল তৈরি হয়েই বন্ধ হয়ে যায়, তার মানে সাধারণত নিচের নেটওয়ার্কটি অস্থিতিশীল বা VPN ট্র্যাফিকে বাধা দিচ্ছে। রাউটারের কাছে যান, অথবা সিগন্যালের সমস্যা যাচাই করতে Wi-Fi ও মোবাইল ডেটার মধ্যে বদল করুন। যদি কেবল একটি নির্দিষ্ট নেটওয়ার্কেই কেটে যায় — অফিস, স্কুল, হোটেল — তবে সেই নেটওয়ার্ক সম্ভবত VPN ট্র্যাফিক ছেঁকে দিচ্ছে, এবং অন্য সার্ভার বা দেশ প্রায়ই কাজ করে। Android-এ এটিও দেখুন যে সিস্টেম অ্যাপটিকে ব্যাকগ্রাউন্ডে বন্ধ করে দিচ্ছে কি না।"
      },
      {
        "id": "wifi_signin",
        "title": "সাইন-ইন প্রয়োজন এমন পাবলিক Wi-Fi",
        "summary": "ক্যাফে, হোটেল, বিমানবন্দর ও ট্রেন প্রায়ই লগইনের আগে সবকিছু আটকে রাখে।",
        "body": "এই নেটওয়ার্কগুলো সব ট্র্যাফিক আটকে রাখে যতক্ষণ না আপনি তাদের সাইন-ইন পাতায় শর্ত মেনে নেন, আর তার আগে VPN সংযুক্ত হতে পারে না। VPN বিচ্ছিন্ন করুন, ব্রাউজার খুলুন এবং যেকোনো সাধারণ ওয়েবসাইট লোড করুন — সাইন-ইন পাতাটি আসার কথা। সেটি সম্পূর্ণ করুন, স্বাভাবিক ব্রাউজিং কাজ করছে কি না দেখুন, তারপরই VPN সংযোগ করুন। কোনো পাতা না এলে ডিভাইস থেকে নেটওয়ার্কটি ভুলে যান এবং আবার যুক্ত হন।"
      },
      {
        "id": "network_blocks_vpn",
        "title": "আপনার নেটওয়ার্ক VPN সংযোগ আটকায়",
        "summary": "কিছু অফিস, স্কুল, হোটেল ও সেবাদাতা ইচ্ছাকৃতভাবে VPN ট্র্যাফিক আটকায়।",
        "body": "অ্যাপটি মোবাইল ডেটায় চললেও যদি কোনো একটি Wi-Fi-তে না চলে, তবে সেই নেটওয়ার্ক ইচ্ছাকৃতভাবে VPN ট্র্যাফিক আটকাচ্ছে। এটি নেটওয়ার্ক পরিচালনাকারীর দেওয়া সীমাবদ্ধতা, অ্যাপের ত্রুটি নয়। অন্য সার্ভার বা দেশ চেষ্টা করুন — সবগুলো একইভাবে আটকানো থাকে না — এবং নেটওয়ার্ক বদলে আবার চেষ্টা করুন। অফিস বা স্কুলের মতো পরিচালিত নেটওয়ার্কে এই বাধা প্রায়ই কেন্দ্রীয়ভাবে প্রয়োগ করা হয় এবং অ্যাপের ভেতর থেকে তা এড়ানো যায় না।"
      },
      {
        "id": "android_battery",
        "title": "Android অ্যাপটিকে ব্যাকগ্রাউন্ডে বন্ধ করছে",
        "summary": "ব্যাটারি সাশ্রয়ের সুবিধা স্ক্রিন বন্ধ থাকলে টানেল বন্ধ করে দিতে পারে।",
        "body": "Android বিদ্যুৎ বাঁচাতে ব্যাকগ্রাউন্ড অ্যাপ জোরালোভাবে বন্ধ করে, যার ফলে আপনার অজান্তেই VPN সেশন শেষ হয়ে যেতে পারে। ডিভাইস সেটিংস খুলুন, অ্যাপসের মধ্যে এই অ্যাপটি খুঁজুন এবং এর ব্যাটারি অপশন Unrestricted বা অবাধ করে দিন (প্রস্তুতকারক ভেদে নাম আলাদা — Samsung, Xiaomi, Huawei ও OnePlus আলাদা শব্দ ব্যবহার করে)। অ্যাপটি কোনো 'স্লিপিং' বা 'সীমিত' তালিকায় নেই তাও নিশ্চিত করুন। পরিবর্তনের পর আবার সংযোগ করুন; স্ক্রিন বন্ধ হলেও সেশন টিকে থাকার কথা।"
      },
      {
        "id": "ios_vpn_permission",
        "title": "iPhone VPN কনফিগারেশনের অনুমতি চায়",
        "summary": "যেকোনো VPN অ্যাপ সংযুক্ত হওয়ার আগে iOS-এর একবার আপনার অনুমতি দরকার।",
        "body": "প্রথমবার সংযোগের সময় iOS একটি VPN কনফিগারেশন যোগ করার অনুমতি চায় এবং পাসকোড বা Face ID চাইতে পারে। এটি iOS-এর স্বাভাবিক অনুরোধ এবং অনুমতি না দিলে অ্যাপ সংযুক্ত হতে পারে না। আগে প্রত্যাখ্যান করে থাকলে Settings, তারপর General, তারপর VPN ও Device Management-এ যান, এই অ্যাপের পুরোনো কনফিগারেশন মুছুন, এবং নতুন অনুরোধ পেতে আবার সংযোগ করুন। অন্য কোনো VPN অ্যাপ ইনস্টল থাকলে নিশ্চিত করুন সেটি বিচ্ছিন্ন আছে — একসঙ্গে কেবল একটি VPN সক্রিয় থাকতে পারে।"
      },
      {
        "id": "device_clock",
        "title": "আপনার ডিভাইসের তারিখ ও সময় ভুল",
        "summary": "কয়েক মিনিটের বেশি ভুল ঘড়ি নিরাপদ হ্যান্ডশেক ভেঙে দেয়।",
        "body": "নিরাপদ সংযোগ বর্তমান সময়ের সঙ্গে মিলিয়ে সার্টিফিকেট যাচাই করে, তাই ভুল ঘড়ির ডিভাইস নিখুঁত নেটওয়ার্কেও সংযুক্ত হতে ব্যর্থ হবে। ডিভাইস সেটিংস খুলুন, তারিখ ও সময় স্বয়ংক্রিয়ভাবে সেট হওয়ার অপশন চালু করুন, তারপর আবার সংযোগ করুন। এই কারণটি সহজে চোখ এড়িয়ে যায়, কারণ ডিভাইসের বাকি সবকিছু স্বাভাবিকভাবেই কাজ করতে দেখা যায়।"
      },
      {
        "id": "slow_speed",
        "title": "সংযোগ ধীরগতির",
        "summary": "গতি মূলত সার্ভারের দূরত্ব ও তার ব্যস্ততার উপর নির্ভর করে।",
        "body": "VPN সবসময়ই কিছুটা গতি কমায়, কারণ আপনার ট্র্যাফিক দীর্ঘ পথ পাড়ি দেয় এবং পথে এনক্রিপ্ট হয়। কাছের সার্ভার বেছে নিন — কাছের দেশ প্রায় সবসময়ই দূরের দেশের চেয়ে দ্রুত। কোনো সার্ভারে বাঁ দিকে সোয়াইপ করে PING চাপুন, দেখুন সেটি কত দ্রুত সাড়া দেয়; কম সংখ্যা ভালো। ফ্রি সার্ভার বহু মানুষ ভাগ করে নেয় এবং ব্যস্ত সময়ে বেশি ভিড় থাকে; প্রিমিয়াম সার্ভারে ব্যবহারকারী কম। VPN বন্ধ রেখেও একবার গতি মেপে নিন, যাতে জানেন আপনার সংযোগ আসলে কতটা দিতে পারে।"
      },
      {
        "id": "streaming_blocked",
        "title": "কোনো স্ট্রিমিং সেবা কাজ করছে না",
        "summary": "বড় স্ট্রিমিং প্ল্যাটফর্মগুলো সক্রিয়ভাবে VPN শনাক্ত করে ও আটকায়।",
        "body": "লাইসেন্সের কারণে স্ট্রিমিং সেবাগুলোকে দেশভিত্তিকভাবে কনটেন্ট দেখাতে হয়, তাই তারা VPN ট্র্যাফিক শনাক্ত ও আটকাতে বিপুল বিনিয়োগ করে। এটি কেবল এই অ্যাপ নয়, সব VPN-এর ক্ষেত্রেই প্রযোজ্য, আর আজ যে সার্ভার কাজ করছে কাল সেটি শনাক্ত হয়ে যেতে পারে। অন্য সার্ভার চেষ্টা করলে কখনও কাজ হয়, তবে কোনো VPN-ই নির্দিষ্ট কোনো স্ট্রিমিং সেবায় প্রবেশের প্রতিশ্রুতি দিতে পারে না, আর আমরাও তার নিশ্চয়তা দিতে পারি না।"
      },
      {
        "id": "free_time_limit",
        "title": "আপনার ফ্রি সংযোগ সময় শেষ হয়ে গেছে",
        "summary": "ফ্রি সার্ভারে প্রতিদিন নির্দিষ্ট পরিমাণ সংযোগ সময় থাকে।",
        "body": "ফ্রি সার্ভারের সঙ্গে প্রতিদিনের একটি সংযোগ সময়সীমা থাকে, যা প্রতিদিন নতুন করে শুরু হয়। সময় ফুরিয়ে গেলে একটি ছোট ভিডিও দেখে তা বাড়ানো যায়, দিনে সীমিত সংখ্যকবার। ফ্রি সংস্করণের খরচ এভাবেই ওঠে, তাই এটি পরিকল্পিতভাবেই এমন, কোনো ত্রুটি নয়। সাবস্ক্রিপশন নিলে সময়সীমা পুরোপুরি উঠে যায়, সব সার্ভার খুলে যায় এবং বিজ্ঞাপন সরে যায়।"
      },
      {
        "id": "subscription_help",
        "title": "সাবস্ক্রিপশন, পুনরুদ্ধার ও রিফান্ড",
        "summary": "কেনাকাটা পরিচালনা করে App Store ও Google Play, আমরা নই।",
        "body": "সাবস্ক্রিপশন নেওয়ার পরও অ্যাপ যদি ফ্রি সংস্করণ দেখায়, সাবস্ক্রিপশন স্ক্রিন খুলে 'কেনাকাটা পুনরুদ্ধার করুন' চাপুন, এবং নিশ্চিত করুন যে আপনি সেই অ্যাকাউন্টেই সাইন ইন আছেন যেটি দিয়ে কিনেছিলেন। সাবস্ক্রিপশন স্বয়ংক্রিয়ভাবে নবায়ন হয় এবং আপনার স্টোর অ্যাকাউন্ট থেকেই বাতিল করতে হয় — iPhone-এ আপনার Apple অ্যাকাউন্টের সাবস্ক্রিপশনে, Android-এ Play Store-এর পেমেন্ট ও সাবস্ক্রিপশন অংশে। রিফান্ড স্টোর দেয়, তাই অনুরোধ Apple বা Google-এর কাছেই করতে হবে।"
      }
    ]
  },
  "de": {
    "lang": "de",
    "dir": "ltr",
    "label": "Deutsch",
    "heading": "Hilfe",
    "back": "← Alle Themen",
    "stillStuck": "Immer noch ein Problem? Schreiben Sie uns an",
    "articles": [
      {
        "id": "cannot_connect",
        "title": "Die App verbindet sich nicht",
        "summary": "Verbindungsversuche schlagen fehl oder werden nie fertig.",
        "body": "Probieren Sie zuerst einen anderen Server — ein einzelner Server kann ausgelastet oder vorübergehend nicht erreichbar sein, und ein Wechsel geht schneller als jede andere Lösung. Öffnen Sie Serverstandort, wählen Sie ein anderes Land und verbinden Sie erneut. Wenn kein Server funktioniert, schalten Sie WLAN aus und nutzen Sie mobile Daten (oder umgekehrt): meist liegt es am Netzwerk, nicht an der App. Hilft das nicht, starten Sie Ihr Gerät neu und versuchen Sie es nochmals. Die meisten Verbindungsfehler verursacht das Netzwerk, in dem Sie sich befinden — deshalb löst ein Wechsel von Netzwerk oder Server die große Mehrheit davon."
      },
      {
        "id": "keeps_dropping",
        "title": "Die Verbindung bricht immer wieder ab",
        "summary": "Sie verbinden sich erfolgreich und werden dann wieder getrennt.",
        "body": "Ein Tunnel, der sich öffnet und wieder schließt, bedeutet meist, dass das darunterliegende Netzwerk instabil ist oder VPN-Verkehr stört. Gehen Sie näher an den Router oder wechseln Sie zwischen WLAN und mobilen Daten, um Signalprobleme auszuschließen. Bricht es nur in einem bestimmten Netzwerk ab — Büro, Schule, Hotel — filtert dieses Netzwerk wahrscheinlich VPN-Verkehr, und ein anderer Server oder ein anderes Land kommt oft durch. Prüfen Sie unter Android außerdem, ob das System die App im Hintergrund beendet."
      },
      {
        "id": "wifi_signin",
        "title": "Öffentliches WLAN mit Anmeldeseite",
        "summary": "Cafés, Hotels, Flughäfen und Züge blockieren oft alles bis zur Anmeldung.",
        "body": "Diese Netzwerke halten jeglichen Datenverkehr zurück, bis Sie deren Bedingungen auf einer Anmeldeseite akzeptieren — davor kann sich ein VPN nicht verbinden. Trennen Sie das VPN, öffnen Sie Ihren Browser und laden Sie eine beliebige einfache Website; die Anmeldeseite sollte erscheinen. Schließen Sie sie ab, prüfen Sie, ob normales Surfen funktioniert, und verbinden Sie erst dann das VPN. Erscheint keine Seite, entfernen Sie das Netzwerk auf Ihrem Gerät und verbinden Sie sich neu."
      },
      {
        "id": "network_blocks_vpn",
        "title": "Ihr Netzwerk blockiert VPN-Verbindungen",
        "summary": "Manche Büros, Schulen, Hotels und Anbieter blockieren VPN-Verkehr bewusst.",
        "body": "Wenn die App über mobile Daten funktioniert, aber in einem bestimmten WLAN nicht, blockiert dieses Netzwerk VPN-Verkehr absichtlich. Das ist eine Einschränkung des Netzwerkbetreibers und kein Fehler der App. Probieren Sie einen anderen Server oder ein anderes Land — nicht alle sind gleich blockiert — und versuchen Sie es nach einem Netzwerkwechsel erneut. In verwalteten Netzwerken, etwa in Firmen oder Schulen, wird die Sperre oft zentral durchgesetzt und lässt sich aus der App heraus nicht umgehen."
      },
      {
        "id": "android_battery",
        "title": "Android schließt die App im Hintergrund",
        "summary": "Energiesparfunktionen können den Tunnel bei ausgeschaltetem Display beenden.",
        "body": "Android beendet Hintergrund-Apps konsequent, um Strom zu sparen, und kann so eine VPN-Sitzung beenden, während Sie nicht hinsehen. Öffnen Sie die Geräteeinstellungen, suchen Sie diese App unter Apps und stellen Sie die Akku-Option auf Uneingeschränkt (die Bezeichnung unterscheidet sich je nach Hersteller — Samsung, Xiaomi, Huawei und OnePlus formulieren es jeweils anders). Achten Sie außerdem darauf, dass die App in keiner Liste für schlafende oder eingeschränkte Apps steht. Verbinden Sie danach erneut; die Sitzung sollte das Ausschalten des Displays überstehen."
      },
      {
        "id": "ios_vpn_permission",
        "title": "iPhone fragt nach einer VPN-Konfiguration",
        "summary": "iOS benötigt einmalig Ihre Erlaubnis, bevor sich eine VPN-App verbinden kann.",
        "body": "Beim ersten Verbinden fragt iOS, ob eine VPN-Konfiguration hinzugefügt werden darf, und verlangt eventuell Ihren Code oder Face ID. Das ist eine normale iOS-Abfrage, und die App kann sich erst danach verbinden. Haben Sie sie zuvor abgelehnt, gehen Sie zu Einstellungen, dann Allgemein, dann VPN & Geräteverwaltung, entfernen Sie alte Konfigurationen dieser App und verbinden Sie erneut, um die Abfrage neu zu erhalten. Ist eine weitere VPN-App installiert, stellen Sie sicher, dass sie getrennt ist — es kann immer nur ein VPN aktiv sein."
      },
      {
        "id": "device_clock",
        "title": "Datum und Uhrzeit Ihres Geräts sind falsch",
        "summary": "Eine Uhr, die mehr als ein paar Minuten abweicht, verhindert den sicheren Handshake.",
        "body": "Sichere Verbindungen prüfen Zertifikate gegen die aktuelle Uhrzeit. Ein Gerät mit falscher Uhr kann sich daher selbst in einem einwandfreien Netzwerk nicht verbinden. Öffnen Sie die Geräteeinstellungen, aktivieren Sie Datum und Uhrzeit automatisch und verbinden Sie erneut. Das wird leicht übersehen, weil alles andere auf dem Gerät normal zu funktionieren scheint."
      },
      {
        "id": "slow_speed",
        "title": "Die Verbindung ist langsam",
        "summary": "Das Tempo hängt vor allem von der Entfernung zum Server und dessen Auslastung ab.",
        "body": "Ein VPN kostet immer etwas Geschwindigkeit, weil Ihr Datenverkehr einen längeren Weg nimmt und unterwegs verschlüsselt wird. Wählen Sie einen Server in Ihrer Nähe — ein nahes Land ist fast immer schneller als ein fernes. Wischen Sie einen Server nach links und tippen Sie auf PING, um zu sehen, wie schnell er antwortet; ein niedriger Wert ist besser. Kostenlose Server teilen sich viele Nutzer und sind zu Stoßzeiten voller, Premium-Server tragen weniger Nutzer. Messen Sie Ihr Tempo auch ohne VPN, damit Sie wissen, was Ihre Leitung wirklich leistet."
      },
      {
        "id": "streaming_blocked",
        "title": "Ein Streamingdienst funktioniert nicht",
        "summary": "Große Streaming-Plattformen erkennen und blockieren VPNs aktiv.",
        "body": "Streamingdienste müssen ihre Inhalte lizenzbedingt länderweise ausspielen und investieren deshalb viel in das Erkennen und Blockieren von VPN-Verkehr. Das betrifft jedes VPN, nicht nur diese App, und ein Server, der heute funktioniert, kann morgen erkannt sein. Ein anderer Server hilft manchmal, aber kein VPN kann den Zugang zu einem bestimmten Streamingdienst zusichern, und wir können ihn nicht garantieren."
      },
      {
        "id": "free_time_limit",
        "title": "Ihre kostenlose Verbindungszeit ist aufgebraucht",
        "summary": "Kostenlose Server enthalten täglich ein festes Zeitkontingent.",
        "body": "Kostenlose Server haben ein tägliches Zeitkontingent, das sich jeden Tag erneuert. Ist es aufgebraucht, können Sie es durch ein kurzes Video verlängern — eine begrenzte Anzahl Male pro Tag. So finanziert sich die kostenlose Version; es ist also beabsichtigt und kein Fehler. Ein Abonnement hebt das Zeitlimit vollständig auf, schaltet alle Server frei und entfernt die Werbung."
      },
      {
        "id": "subscription_help",
        "title": "Abonnement, Wiederherstellen und Erstattungen",
        "summary": "Käufe wickeln der App Store und Google Play ab, nicht wir.",
        "body": "Wenn Sie abonniert haben und die App weiterhin die kostenlose Version zeigt, öffnen Sie den Abo-Bildschirm und tippen Sie auf Käufe wiederherstellen — achten Sie darauf, mit dem Konto angemeldet zu sein, mit dem Sie gekauft haben. Abonnements verlängern sich automatisch und werden in Ihrem Store-Konto gekündigt: auf dem iPhone unter den Abos Ihres Apple-Accounts, auf Android unter Zahlungen und Abos im Play Store. Erstattungen leistet der Store, Anfragen laufen daher über Apple oder Google."
      }
    ]
  },
  "hi": {
    "lang": "hi",
    "dir": "ltr",
    "label": "हिन्दी",
    "heading": "सहायता",
    "back": "← सभी विषय",
    "stillStuck": "अब भी समस्या है? हमें ईमेल करें",
    "articles": [
      {
        "id": "cannot_connect",
        "title": "ऐप कनेक्ट नहीं हो रहा",
        "summary": "कनेक्शन के प्रयास विफल हो जाते हैं या कभी पूरे नहीं होते।",
        "body": "पहले कोई दूसरा सर्वर आज़माएँ — कोई एक सर्वर व्यस्त या कुछ समय के लिए बंद हो सकता है, और सर्वर बदलना बाकी सभी उपायों से तेज़ है। सर्वर लोकेशन खोलें, कोई दूसरा देश चुनें और फिर से कनेक्ट करें। अगर कोई भी सर्वर काम न करे, तो Wi-Fi बंद करके मोबाइल डेटा आज़माएँ (या इसका उल्टा): समस्या आमतौर पर नेटवर्क की होती है, ऐप की नहीं। फिर भी नहीं चला? डिवाइस को रीस्टार्ट करें और एक बार और कोशिश करें। अधिकांश कनेक्शन विफलताओं की वजह वही नेटवर्क होता है जिस पर आप हैं, इसीलिए नेटवर्क या सर्वर बदलने से उनमें से ज़्यादातर ठीक हो जाती हैं।"
      },
      {
        "id": "keeps_dropping",
        "title": "कनेक्शन बार-बार टूट रहा है",
        "summary": "कनेक्शन सफलतापूर्वक बनता है, फिर टूट जाता है।",
        "body": "जो टनल बनकर तुरंत बंद हो जाए, उसका आमतौर पर मतलब है कि नीचे का नेटवर्क अस्थिर है या VPN ट्रैफ़िक में बाधा डाल रहा है। राउटर के पास जाएँ, या सिग्नल की समस्या जाँचने के लिए Wi-Fi और मोबाइल डेटा के बीच बदलें। अगर यह सिर्फ़ किसी एक नेटवर्क पर टूटता है — दफ़्तर, स्कूल, होटल — तो संभवतः वह नेटवर्क VPN ट्रैफ़िक छान रहा है, और कोई दूसरा सर्वर या देश अक्सर काम कर जाता है। Android पर यह भी देखें कि सिस्टम ऐप को बैकग्राउंड में बंद तो नहीं कर रहा।"
      },
      {
        "id": "wifi_signin",
        "title": "सार्वजनिक Wi-Fi जिसमें साइन-इन ज़रूरी है",
        "summary": "कैफ़े, होटल, हवाई अड्डे और ट्रेनें अक्सर लॉगिन से पहले सब कुछ रोक देते हैं।",
        "body": "ऐसे नेटवर्क तब तक पूरा ट्रैफ़िक रोके रखते हैं जब तक आप उनके साइन-इन पेज पर शर्तें स्वीकार न कर लें, और उससे पहले VPN कनेक्ट नहीं हो सकता। VPN बंद करें, ब्राउज़र खोलें और कोई भी सामान्य वेबसाइट खोलें — साइन-इन पेज दिखना चाहिए। उसे पूरा करें, देख लें कि सामान्य ब्राउज़िंग चल रही है, और उसके बाद ही VPN कनेक्ट करें। अगर कोई पेज न दिखे, तो डिवाइस पर उस नेटवर्क को भूलें और दोबारा जुड़ें।"
      },
      {
        "id": "network_blocks_vpn",
        "title": "आपका नेटवर्क VPN कनेक्शन रोकता है",
        "summary": "कुछ दफ़्तर, स्कूल, होटल और सेवा प्रदाता जानबूझकर VPN ट्रैफ़िक रोकते हैं।",
        "body": "अगर ऐप मोबाइल डेटा पर चलता है लेकिन किसी एक Wi-Fi पर नहीं, तो वह नेटवर्क जानबूझकर VPN ट्रैफ़िक रोक रहा है। यह नेटवर्क चलाने वाले की लगाई पाबंदी है, ऐप की खराबी नहीं। कोई दूसरा सर्वर या देश आज़माएँ — सभी एक ही तरह से नहीं रोके जाते — और नेटवर्क बदलने के बाद फिर कोशिश करें। कंपनी या स्कूल जैसे प्रबंधित नेटवर्क में यह रोक अक्सर केंद्रीय रूप से लागू होती है और ऐप के भीतर से इसे पार नहीं किया जा सकता।"
      },
      {
        "id": "android_battery",
        "title": "Android ऐप को बैकग्राउंड में बंद कर रहा है",
        "summary": "बैटरी बचाने वाली सुविधाएँ स्क्रीन बंद होने पर टनल बंद कर सकती हैं।",
        "body": "Android बिजली बचाने के लिए बैकग्राउंड ऐप्स को सख़्ती से बंद करता है, जिससे आपकी जानकारी के बिना VPN सत्र समाप्त हो सकता है। डिवाइस सेटिंग खोलें, ऐप्स में इस ऐप को ढूँढें और इसकी बैटरी सेटिंग को अप्रतिबंधित (Unrestricted) करें — हर निर्माता का शब्द अलग है, Samsung, Xiaomi, Huawei और OnePlus सबका अपना नाम है। यह भी देखें कि ऐप किसी 'स्लीपिंग' या 'प्रतिबंधित' सूची में न हो। बदलाव के बाद दोबारा कनेक्ट करें; अब स्क्रीन बंद होने पर भी सत्र बना रहना चाहिए।"
      },
      {
        "id": "ios_vpn_permission",
        "title": "iPhone VPN कॉन्फ़िगरेशन की अनुमति माँगता है",
        "summary": "किसी भी VPN ऐप के कनेक्ट होने से पहले iOS को एक बार आपकी अनुमति चाहिए।",
        "body": "पहली बार कनेक्ट करते समय iOS एक VPN कॉन्फ़िगरेशन जोड़ने की अनुमति माँगता है और पासकोड या Face ID भी माँग सकता है। यह iOS का सामान्य संकेत है और अनुमति दिए बिना ऐप कनेक्ट नहीं हो सकता। अगर आपने पहले मना कर दिया था, तो सेटिंग्स, फिर जनरल, फिर VPN और डिवाइस प्रबंधन में जाएँ, इस ऐप का पुराना कॉन्फ़िगरेशन हटाएँ, और नया संकेत पाने के लिए फिर से कनेक्ट करें। अगर कोई दूसरा VPN ऐप इंस्टॉल है, तो देख लें कि वह डिसकनेक्ट हो — एक समय पर सिर्फ़ एक ही VPN सक्रिय रह सकता है।"
      },
      {
        "id": "device_clock",
        "title": "आपके डिवाइस की तारीख़ और समय ग़लत हैं",
        "summary": "कुछ मिनट से ज़्यादा ग़लत घड़ी सुरक्षित हैंडशेक तोड़ देती है।",
        "body": "सुरक्षित कनेक्शन प्रमाणपत्रों को मौजूदा समय से जाँचते हैं, इसलिए ग़लत घड़ी वाला डिवाइस बिल्कुल ठीक नेटवर्क पर भी कनेक्ट नहीं हो पाएगा। डिवाइस सेटिंग खोलें, तारीख़ और समय अपने आप सेट होने का विकल्प चालू करें, फिर दोबारा कनेक्ट करें। इस वजह पर ध्यान आसानी से नहीं जाता, क्योंकि डिवाइस पर बाकी सब कुछ सामान्य लगता है।"
      },
      {
        "id": "slow_speed",
        "title": "कनेक्शन धीमा है",
        "summary": "गति मुख्य रूप से सर्वर की दूरी और उस पर भीड़ पर निर्भर करती है।",
        "body": "VPN से हमेशा कुछ गति कम होती है, क्योंकि आपका ट्रैफ़िक लंबा रास्ता लेता है और रास्ते में एन्क्रिप्ट होता है। अपने पास का सर्वर चुनें — नज़दीकी देश लगभग हमेशा दूर के देश से तेज़ होता है। किसी सर्वर को बाईं ओर स्वाइप करें और PING दबाएँ ताकि पता चले कि वह कितनी जल्दी जवाब देता है; कम संख्या बेहतर है। मुफ़्त सर्वर बहुत से लोग साझा करते हैं और व्यस्त समय में अधिक भरे रहते हैं, जबकि प्रीमियम सर्वर पर कम उपयोगकर्ता होते हैं। VPN बंद करके भी अपनी गति जाँचें, ताकि पता चले कि आपका कनेक्शन असल में कितना दे सकता है।"
      },
      {
        "id": "streaming_blocked",
        "title": "कोई स्ट्रीमिंग सेवा काम नहीं कर रही",
        "summary": "बड़े स्ट्रीमिंग प्लेटफ़ॉर्म VPN को सक्रिय रूप से पहचानते और रोकते हैं।",
        "body": "लाइसेंस के कारण स्ट्रीमिंग सेवाओं को सामग्री देश के अनुसार दिखानी होती है, इसलिए वे VPN ट्रैफ़िक पहचानने और रोकने में बहुत निवेश करती हैं। यह हर VPN पर लागू होता है, सिर्फ़ इस ऐप पर नहीं, और जो सर्वर आज चलता है वह कल पहचाना जा सकता है। कभी-कभी दूसरा सर्वर मदद करता है, लेकिन कोई भी VPN किसी ख़ास स्ट्रीमिंग सेवा तक पहुँच का वादा नहीं कर सकता, और हम इसकी गारंटी नहीं दे सकते।"
      },
      {
        "id": "free_time_limit",
        "title": "आपका मुफ़्त कनेक्शन समय समाप्त हो गया",
        "summary": "मुफ़्त सर्वर में हर दिन तय मात्रा में कनेक्शन समय मिलता है।",
        "body": "मुफ़्त सर्वर के साथ हर दिन कनेक्शन समय की एक सीमा मिलती है, जो रोज़ नए सिरे से मिलती है। समय ख़त्म होने पर आप एक छोटा वीडियो देखकर इसे बढ़ा सकते हैं, दिन में सीमित बार। मुफ़्त संस्करण का ख़र्च इसी से निकलता है, इसलिए यह जानबूझकर बनाया गया तरीक़ा है, कोई ख़राबी नहीं। सदस्यता लेने पर समय की सीमा पूरी तरह हट जाती है, सभी सर्वर खुल जाते हैं और विज्ञापन हट जाते हैं।"
      },
      {
        "id": "subscription_help",
        "title": "सदस्यता, पुनर्स्थापना और रिफ़ंड",
        "summary": "ख़रीदारी App Store और Google Play संभालते हैं, हम नहीं।",
        "body": "अगर आपने सदस्यता ली है और ऐप अब भी मुफ़्त संस्करण दिखा रहा है, तो सदस्यता स्क्रीन खोलें और 'ख़रीदारी पुनर्स्थापित करें' दबाएँ, यह सुनिश्चित करते हुए कि आप उसी खाते से साइन इन हैं जिससे ख़रीदा था। सदस्यताएँ अपने आप नवीनीकृत होती हैं और आपके स्टोर खाते से ही रद्द होती हैं — iPhone पर आपके Apple खाते की सदस्यताओं में, Android पर Play Store के भुगतान और सदस्यता अनुभाग में। रिफ़ंड स्टोर जारी करता है, इसलिए अनुरोध Apple या Google के पास भेजना होगा।"
      }
    ]
  },
  "id": {
    "lang": "id",
    "dir": "ltr",
    "label": "Indonesia",
    "heading": "Bantuan",
    "back": "← Semua topik",
    "stillStuck": "Masih bermasalah? Kirim email ke",
    "articles": [
      {
        "id": "cannot_connect",
        "title": "Aplikasi tidak bisa terhubung",
        "summary": "Upaya koneksi gagal atau tidak pernah selesai.",
        "body": "Coba server lain terlebih dahulu — satu server bisa saja penuh atau sedang bermasalah, dan berpindah server lebih cepat daripada solusi lain. Buka Lokasi server, pilih negara lain, lalu hubungkan kembali. Jika tidak ada server yang berhasil, matikan Wi-Fi dan gunakan data seluler (atau sebaliknya): masalahnya biasanya pada jaringan, bukan aplikasi. Masih belum berhasil? Mulai ulang perangkat Anda, lalu coba sekali lagi. Sebagian besar kegagalan koneksi disebabkan oleh jaringan yang Anda gunakan, itulah sebabnya mengganti jaringan atau server menyelesaikan sebagian besar di antaranya."
      },
      {
        "id": "keeps_dropping",
        "title": "Koneksi terus terputus",
        "summary": "Anda berhasil terhubung, lalu terputus lagi.",
        "body": "Terowongan yang terbuka lalu tertutup biasanya berarti jaringan di bawahnya tidak stabil atau mengganggu lalu lintas VPN. Dekatkan diri ke router atau beralih antara Wi-Fi dan data seluler untuk memastikan bukan masalah sinyal. Jika hanya terputus di satu jaringan — kantor, sekolah, hotel — jaringan tersebut kemungkinan menyaring lalu lintas VPN, dan server atau negara lain sering kali bisa tembus. Di Android, periksa juga apakah sistem menutup aplikasi di latar belakang."
      },
      {
        "id": "wifi_signin",
        "title": "Wi-Fi publik yang memerlukan login",
        "summary": "Kafe, hotel, bandara, dan kereta sering memblokir semuanya sampai Anda masuk.",
        "body": "Jaringan seperti ini menahan semua lalu lintas sampai Anda menyetujui ketentuan di halaman login, dan VPN tidak bisa terhubung sebelum itu. Putuskan VPN, buka peramban, dan muat situs biasa apa pun — halaman login seharusnya muncul. Selesaikan login, pastikan browsing normal berfungsi, baru kemudian hubungkan VPN. Jika tidak ada halaman yang muncul, lupakan jaringan tersebut di perangkat Anda lalu sambungkan kembali."
      },
      {
        "id": "network_blocks_vpn",
        "title": "Jaringan Anda memblokir koneksi VPN",
        "summary": "Sebagian kantor, sekolah, hotel, dan penyedia sengaja memblokir lalu lintas VPN.",
        "body": "Jika aplikasi berfungsi dengan data seluler tetapi tidak pada satu jaringan Wi-Fi tertentu, jaringan itu sengaja memblokir lalu lintas VPN. Ini pembatasan dari pengelola jaringan, bukan kesalahan aplikasi. Coba server atau negara lain — tidak semuanya diblokir dengan cara yang sama — dan coba lagi setelah berganti jaringan. Pada jaringan terkelola, seperti milik perusahaan atau sekolah, pemblokiran biasanya diterapkan secara terpusat dan tidak dapat dilewati dari dalam aplikasi."
      },
      {
        "id": "android_battery",
        "title": "Android menutup aplikasi di latar belakang",
        "summary": "Fitur hemat baterai dapat menghentikan terowongan saat layar mati.",
        "body": "Android agresif menghentikan aplikasi latar belakang demi menghemat daya, dan itu bisa mengakhiri sesi VPN tanpa Anda sadari. Buka pengaturan perangkat, cari aplikasi ini di bagian Aplikasi, lalu setel opsi baterainya menjadi Tidak dibatasi (penyebutannya berbeda tiap produsen — Samsung, Xiaomi, Huawei, dan OnePlus memakai istilah masing-masing). Pastikan juga aplikasi tidak masuk daftar aplikasi yang 'ditidurkan' atau 'dibatasi'. Setelah itu, hubungkan kembali dan sesi seharusnya bertahan meski layar dimatikan."
      },
      {
        "id": "ios_vpn_permission",
        "title": "iPhone meminta izin konfigurasi VPN",
        "summary": "iOS memerlukan izin Anda sekali sebelum aplikasi VPN mana pun bisa terhubung.",
        "body": "Saat pertama kali terhubung, iOS meminta izin menambahkan konfigurasi VPN dan mungkin meminta kode sandi atau Face ID. Ini permintaan standar iOS dan aplikasi tidak bisa terhubung sampai Anda mengizinkannya. Jika sebelumnya Anda menolak, buka Pengaturan, lalu Umum, lalu VPN & Manajemen Perangkat, hapus konfigurasi lama untuk aplikasi ini, dan hubungkan lagi untuk memunculkan permintaan baru. Jika ada aplikasi VPN lain yang terpasang, pastikan aplikasi itu terputus — hanya satu VPN yang bisa aktif pada satu waktu."
      },
      {
        "id": "device_clock",
        "title": "Tanggal dan waktu perangkat salah",
        "summary": "Jam yang meleset lebih dari beberapa menit merusak jabat tangan aman.",
        "body": "Koneksi aman memeriksa sertifikat berdasarkan waktu saat ini, sehingga perangkat dengan jam yang salah akan gagal terhubung bahkan di jaringan yang sempurna. Buka pengaturan perangkat, aktifkan tanggal dan waktu otomatis, lalu hubungkan kembali. Penyebab ini mudah terlewat karena semua hal lain di perangkat tampak berfungsi normal."
      },
      {
        "id": "slow_speed",
        "title": "Koneksinya lambat",
        "summary": "Kecepatan terutama bergantung pada jarak ke server dan seberapa sibuk server itu.",
        "body": "VPN selalu mengurangi sedikit kecepatan, karena lalu lintas Anda menempuh jalur lebih panjang dan dienkripsi di perjalanan. Pilih server yang dekat dengan Anda — negara terdekat hampir selalu lebih cepat daripada yang jauh. Geser server ke kiri dan ketuk PING untuk melihat seberapa cepat server merespons, dan pilih angka yang rendah. Server gratis dipakai bersama oleh banyak orang dan lebih padat pada jam sibuk; server premium melayani lebih sedikit pengguna. Uji juga kecepatan Anda tanpa VPN, agar tahu kemampuan koneksi Anda sebenarnya."
      },
      {
        "id": "streaming_blocked",
        "title": "Layanan streaming tidak berfungsi",
        "summary": "Platform streaming besar aktif mendeteksi dan memblokir VPN.",
        "body": "Layanan streaming diwajibkan lisensinya untuk menayangkan konten per negara, sehingga mereka berinvestasi besar untuk mendeteksi dan memblokir lalu lintas VPN. Ini berlaku untuk semua VPN, bukan hanya aplikasi ini, dan server yang berfungsi hari ini bisa terdeteksi besok. Mencoba server lain kadang membantu, tetapi tidak ada VPN yang bisa menjanjikan akses ke layanan streaming tertentu, dan kami tidak dapat menjaminnya."
      },
      {
        "id": "free_time_limit",
        "title": "Waktu koneksi gratis Anda habis",
        "summary": "Server gratis menyertakan sejumlah waktu koneksi setiap hari.",
        "body": "Server gratis memiliki jatah waktu koneksi harian yang diperbarui setiap hari. Ketika habis, Anda dapat menonton video singkat untuk memperpanjangnya, dengan jumlah terbatas per hari. Begitulah versi gratis dibiayai, jadi ini memang dirancang demikian dan bukan kerusakan. Berlangganan menghapus batas waktu sepenuhnya, membuka semua server, dan menghilangkan iklan."
      },
      {
        "id": "subscription_help",
        "title": "Langganan, pemulihan, dan pengembalian dana",
        "summary": "Pembelian ditangani oleh App Store dan Google Play, bukan oleh kami.",
        "body": "Jika Anda sudah berlangganan tetapi aplikasi masih menampilkan versi gratis, buka layar langganan dan ketuk Pulihkan pembelian, pastikan Anda masuk dengan akun yang dipakai saat membeli. Langganan diperpanjang otomatis dan dibatalkan di akun toko Anda — di iPhone pada langganan Akun Apple Anda, di Android pada Pembayaran dan langganan di Play Store. Pengembalian dana diterbitkan oleh toko, jadi permintaannya harus melalui Apple atau Google."
      }
    ]
  },
  "pt": {
    "lang": "pt",
    "dir": "ltr",
    "label": "Português",
    "heading": "Ajuda",
    "back": "← Todos os tópicos",
    "stillStuck": "Ainda com problema? Escreva para",
    "articles": [
      {
        "id": "cannot_connect",
        "title": "O aplicativo não conecta",
        "summary": "As tentativas de conexão falham ou nunca terminam.",
        "body": "Experimente outro servidor primeiro — um servidor pode estar cheio ou temporariamente fora do ar, e trocar é mais rápido do que qualquer outra solução. Abra Localização do servidor, escolha outro país e conecte novamente. Se nenhum servidor funcionar, desligue o Wi-Fi e use os dados móveis (ou o contrário): o problema costuma ser a rede, não o aplicativo. Ainda nada? Reinicie o aparelho e tente de novo. A maioria das falhas de conexão vem da rede em que você está, por isso trocar de rede ou de servidor resolve a grande maioria delas."
      },
      {
        "id": "keeps_dropping",
        "title": "A conexão cai o tempo todo",
        "summary": "Você conecta com sucesso e logo é desconectado.",
        "body": "Um túnel que abre e fecha em seguida geralmente indica que a rede por baixo está instável ou interfere no tráfego de VPN. Aproxime-se do roteador ou alterne entre Wi-Fi e dados móveis para descartar problemas de sinal. Se só cai em uma rede específica — escritório, escola, hotel — essa rede provavelmente filtra o tráfego de VPN, e outro servidor ou país costuma passar. No Android, verifique também se o sistema não está encerrando o aplicativo em segundo plano."
      },
      {
        "id": "wifi_signin",
        "title": "Wi-Fi público que exige login",
        "summary": "Cafés, hotéis, aeroportos e trens costumam bloquear tudo até você entrar.",
        "body": "Essas redes retêm todo o tráfego até você aceitar os termos em uma página de login, e a VPN não consegue conectar antes disso. Desconecte a VPN, abra o navegador e carregue qualquer site simples — a página de login deve aparecer. Conclua o login, confirme que a navegação normal funciona e só então conecte a VPN. Se nenhuma página aparecer, esqueça a rede no aparelho e entre nela novamente."
      },
      {
        "id": "network_blocks_vpn",
        "title": "Sua rede bloqueia conexões VPN",
        "summary": "Alguns escritórios, escolas, hotéis e provedores bloqueiam VPN de propósito.",
        "body": "Se o aplicativo funciona nos dados móveis mas não em um Wi-Fi específico, essa rede bloqueia o tráfego de VPN de propósito. É uma restrição de quem administra a rede, não uma falha do aplicativo. Tente outro servidor ou país — nem todos são bloqueados da mesma forma — e tente de novo após trocar de rede. Em redes gerenciadas, como de empresas ou escolas, o bloqueio costuma ser aplicado de forma central e não há como contorná-lo pelo aplicativo."
      },
      {
        "id": "android_battery",
        "title": "O Android está fechando o aplicativo em segundo plano",
        "summary": "Recursos de economia de bateria podem encerrar o túnel com a tela desligada.",
        "body": "O Android encerra aplicativos em segundo plano para poupar energia, e isso pode terminar uma sessão de VPN sem você perceber. Abra as configurações do aparelho, encontre este aplicativo em Apps e defina a opção de bateria como Irrestrito (o nome muda conforme o fabricante — Samsung, Xiaomi, Huawei e OnePlus usam termos diferentes). Confira também se o aplicativo não está em alguma lista de apps em suspensão ou restritos. Depois disso, conecte novamente: a sessão deve sobreviver ao desligar da tela."
      },
      {
        "id": "ios_vpn_permission",
        "title": "O iPhone pede permissão para uma configuração de VPN",
        "summary": "O iOS precisa da sua autorização uma vez antes de qualquer VPN conectar.",
        "body": "Na primeira conexão, o iOS pede para adicionar uma configuração de VPN e pode solicitar sua senha ou Face ID. É um aviso padrão do iOS e o aplicativo não consegue conectar até você permitir. Se você recusou antes, vá em Ajustes, Geral, VPN e Gerenciamento de Dispositivos, remova qualquer configuração antiga deste aplicativo e conecte de novo para receber um novo pedido. Se houver outro app de VPN instalado, verifique se ele está desconectado — só uma VPN pode ficar ativa por vez."
      },
      {
        "id": "device_clock",
        "title": "A data e a hora do aparelho estão erradas",
        "summary": "Um relógio com mais de alguns minutos de diferença quebra o handshake seguro.",
        "body": "Conexões seguras conferem certificados em relação à hora atual, então um aparelho com o relógio errado falha ao conectar mesmo em uma rede perfeita. Abra as configurações do aparelho, ative data e hora automáticas e conecte novamente. Esse detalhe passa despercebido com facilidade, porque todo o resto do aparelho parece funcionar normalmente."
      },
      {
        "id": "slow_speed",
        "title": "A conexão está lenta",
        "summary": "A velocidade depende sobretudo da distância até o servidor e de quão cheio ele está.",
        "body": "Uma VPN sempre custa alguma velocidade, porque seu tráfego faz um caminho mais longo e é criptografado no percurso. Escolha um servidor perto de você — um país próximo é quase sempre mais rápido que um distante. Deslize um servidor para a esquerda e toque em PING para ver a rapidez da resposta; prefira o número mais baixo. Servidores gratuitos são compartilhados por muita gente e ficam mais cheios nos horários de pico; os premium carregam menos usuários. Meça também sua velocidade com a VPN desligada, para saber o que sua conexão realmente entrega."
      },
      {
        "id": "streaming_blocked",
        "title": "Um serviço de streaming não funciona",
        "summary": "As grandes plataformas de streaming detectam e bloqueiam VPNs ativamente.",
        "body": "Os serviços de streaming são obrigados por suas licenças a exibir conteúdo por país, por isso investem muito em detectar e bloquear tráfego de VPN. Isso afeta todas as VPNs, não só este aplicativo, e um servidor que funciona hoje pode ser detectado amanhã. Tentar outro servidor às vezes ajuda, mas nenhuma VPN pode prometer acesso a um serviço de streaming específico, e não podemos garanti-lo."
      },
      {
        "id": "free_time_limit",
        "title": "Seu tempo de conexão gratuito acabou",
        "summary": "Os servidores gratuitos incluem uma quantidade de tempo por dia.",
        "body": "Os servidores gratuitos vêm com uma cota diária de tempo de conexão, que é renovada todos os dias. Quando ela acaba, você pode assistir a um vídeo curto para estender, um número limitado de vezes por dia. É assim que a versão gratuita se paga: funciona como planejado, não é uma falha. Uma assinatura remove o limite de tempo por completo, libera todos os servidores e tira os anúncios."
      },
      {
        "id": "subscription_help",
        "title": "Assinaturas, restauração e reembolsos",
        "summary": "As compras são processadas pela App Store e pelo Google Play, não por nós.",
        "body": "Se você assinou e o aplicativo ainda mostra a versão gratuita, abra a tela de assinatura e toque em Restaurar compras, garantindo que está conectado com a conta usada na compra. As assinaturas renovam automaticamente e são canceladas na sua conta da loja — no iPhone, nas assinaturas da sua Conta Apple; no Android, em Pagamentos e assinaturas da Play Store. Os reembolsos são emitidos pela loja, então os pedidos precisam passar pela Apple ou pelo Google."
      }
    ]
  },
  "ru": {
    "lang": "ru",
    "dir": "ltr",
    "label": "Русский",
    "heading": "Помощь",
    "back": "← Все темы",
    "stillStuck": "Проблема осталась? Напишите нам на",
    "articles": [
      {
        "id": "cannot_connect",
        "title": "Приложение не подключается",
        "summary": "Попытки подключения завершаются ошибкой или зависают.",
        "body": "Сначала попробуйте другой сервер — отдельный сервер может быть перегружен или временно недоступен, а смена сервера быстрее любого другого решения. Откройте «Расположение сервера», выберите другую страну и подключитесь снова. Если ни один сервер не работает, выключите Wi-Fi и используйте мобильный интернет (или наоборот): обычно дело в сети, а не в приложении. Не помогло? Перезагрузите устройство и попробуйте ещё раз. Большинство сбоев подключения вызвано сетью, в которой вы находитесь, поэтому смена сети или сервера решает подавляющее большинство из них."
      },
      {
        "id": "keeps_dropping",
        "title": "Соединение постоянно обрывается",
        "summary": "Подключение проходит успешно, но затем связь прерывается.",
        "body": "Туннель, который открывается и сразу закрывается, обычно означает, что сеть под ним нестабильна или мешает VPN-трафику. Подойдите ближе к роутеру или переключитесь между Wi-Fi и мобильным интернетом, чтобы исключить проблемы с сигналом. Если обрывы только в одной сети — в офисе, школе, отеле — эта сеть, скорее всего, фильтрует VPN-трафик, и другой сервер или страна часто проходят. На Android также проверьте, не закрывает ли система приложение в фоне."
      },
      {
        "id": "wifi_signin",
        "title": "Публичный Wi-Fi со страницей входа",
        "summary": "Кафе, отели, аэропорты и поезда часто блокируют всё до входа в сеть.",
        "body": "Такие сети задерживают весь трафик, пока вы не примете условия на странице входа, и до этого VPN подключиться не может. Отключите VPN, откройте браузер и загрузите любой простой сайт — должна появиться страница входа. Пройдите её, убедитесь, что обычный интернет работает, и только затем включайте VPN. Если страница не появляется, удалите сеть на устройстве и подключитесь к ней заново."
      },
      {
        "id": "network_blocks_vpn",
        "title": "Ваша сеть блокирует VPN-подключения",
        "summary": "Некоторые офисы, школы, отели и провайдеры намеренно блокируют VPN.",
        "body": "Если приложение работает через мобильный интернет, но не работает в конкретной сети Wi-Fi, эта сеть блокирует VPN-трафик намеренно. Это ограничение владельца сети, а не сбой приложения. Попробуйте другой сервер или страну — блокируются они по-разному — и повторите попытку после смены сети. В управляемых сетях, например корпоративных или школьных, блокировка обычно действует централизованно, и обойти её из приложения нельзя."
      },
      {
        "id": "android_battery",
        "title": "Android закрывает приложение в фоне",
        "summary": "Энергосбережение может завершить туннель при выключенном экране.",
        "body": "Android активно закрывает фоновые приложения ради экономии заряда, и это может прервать VPN-сессию незаметно для вас. Откройте настройки устройства, найдите это приложение в разделе «Приложения» и задайте для батареи значение «Без ограничений» (формулировка отличается у разных производителей — Samsung, Xiaomi, Huawei и OnePlus называют это по-своему). Также убедитесь, что приложение не попало в списки «спящих» или «ограниченных». После этого подключитесь снова — сессия должна переживать выключение экрана."
      },
      {
        "id": "ios_vpn_permission",
        "title": "iPhone просит разрешить конфигурацию VPN",
        "summary": "iOS один раз запрашивает разрешение, прежде чем любое VPN-приложение сможет подключиться.",
        "body": "При первом подключении iOS просит добавить конфигурацию VPN и может запросить код-пароль или Face ID. Это стандартный запрос iOS, и до вашего согласия приложение подключиться не сможет. Если вы ранее отказали, откройте «Настройки», затем «Основные», затем «VPN и управление устройством», удалите старую конфигурацию этого приложения и подключитесь снова, чтобы запрос появился заново. Если установлено другое VPN-приложение, убедитесь, что оно отключено — активным может быть только один VPN."
      },
      {
        "id": "device_clock",
        "title": "Неверные дата и время на устройстве",
        "summary": "Часы, расходящиеся больше чем на несколько минут, ломают защищённое рукопожатие.",
        "body": "Защищённые соединения сверяют сертификаты с текущим временем, поэтому устройство с неверными часами не подключится даже в идеальной сети. Откройте настройки устройства, включите автоматические дату и время и подключитесь снова. Эту причину легко упустить, потому что всё остальное на устройстве работает как обычно."
      },
      {
        "id": "slow_speed",
        "title": "Соединение медленное",
        "summary": "Скорость зависит прежде всего от расстояния до сервера и его загруженности.",
        "body": "VPN всегда немного снижает скорость, потому что трафик идёт более длинным путём и шифруется в дороге. Выбирайте сервер поближе — соседняя страна почти всегда быстрее дальней. Проведите по серверу влево и нажмите PING, чтобы увидеть скорость отклика; меньшее число лучше. Бесплатными серверами пользуется много людей, и в часы пик они загружены сильнее, а на премиум-серверах пользователей меньше. Измерьте скорость и с выключенным VPN, чтобы знать реальные возможности вашего канала."
      },
      {
        "id": "streaming_blocked",
        "title": "Стриминговый сервис не работает",
        "summary": "Крупные стриминговые платформы активно выявляют и блокируют VPN.",
        "body": "Лицензии обязывают стриминговые сервисы показывать контент по странам, поэтому они вкладывают много сил в обнаружение и блокировку VPN-трафика. Это касается любого VPN, а не только этого приложения, и сервер, работающий сегодня, завтра может быть распознан. Иногда помогает другой сервер, но ни один VPN не может обещать доступ к конкретному стриминговому сервису, и мы не можем это гарантировать."
      },
      {
        "id": "free_time_limit",
        "title": "Бесплатное время подключения закончилось",
        "summary": "Бесплатные серверы включают определённое время подключения в день.",
        "body": "У бесплатных серверов есть суточный лимит времени подключения, который обновляется каждый день. Когда он исчерпан, можно посмотреть короткое видео и продлить время — ограниченное число раз в день. Так окупается бесплатная версия: это задумано так, а не является сбоем. Подписка полностью снимает ограничение по времени, открывает все серверы и убирает рекламу."
      },
      {
        "id": "subscription_help",
        "title": "Подписка, восстановление и возвраты",
        "summary": "Покупки обрабатывают App Store и Google Play, а не мы.",
        "body": "Если вы оформили подписку, а приложение всё ещё показывает бесплатную версию, откройте экран подписки и нажмите «Восстановить покупки», убедившись, что вошли в аккаунт, с которого покупали. Подписки продлеваются автоматически, а отменяются в аккаунте магазина: на iPhone — в подписках вашего Apple Account, на Android — в разделе «Платежи и подписки» в Play Маркете. Возвраты оформляет магазин, поэтому обращаться нужно в Apple или Google."
      }
    ]
  },
  "vi": {
    "lang": "vi",
    "dir": "ltr",
    "label": "Tiếng Việt",
    "heading": "Trợ giúp",
    "back": "← Tất cả chủ đề",
    "stillStuck": "Vẫn chưa được? Gửi email cho chúng tôi tại",
    "articles": [
      {
        "id": "cannot_connect",
        "title": "Ứng dụng không kết nối được",
        "summary": "Các lần thử kết nối thất bại hoặc không bao giờ hoàn tất.",
        "body": "Hãy thử một máy chủ khác trước — một máy chủ có thể đang quá tải hoặc tạm thời ngừng hoạt động, và việc đổi máy chủ nhanh hơn mọi cách khác. Mở Vị trí máy chủ, chọn một quốc gia khác rồi kết nối lại. Nếu không máy chủ nào hoạt động, hãy tắt Wi-Fi và dùng dữ liệu di động (hoặc ngược lại): vấn đề thường nằm ở mạng chứ không phải ứng dụng. Vẫn không được? Khởi động lại thiết bị rồi thử lần nữa. Phần lớn lỗi kết nối là do mạng bạn đang dùng, nên việc đổi mạng hoặc đổi máy chủ giải quyết được đa số trường hợp."
      },
      {
        "id": "keeps_dropping",
        "title": "Kết nối liên tục bị ngắt",
        "summary": "Bạn kết nối thành công rồi lại bị ngắt.",
        "body": "Đường hầm vừa mở đã đóng thường có nghĩa là mạng bên dưới không ổn định hoặc đang cản trở lưu lượng VPN. Hãy đến gần bộ định tuyến hơn, hoặc chuyển qua lại giữa Wi-Fi và dữ liệu di động để loại trừ vấn đề tín hiệu. Nếu chỉ bị ngắt trên một mạng cụ thể — văn phòng, trường học, khách sạn — thì mạng đó nhiều khả năng đang lọc lưu lượng VPN, và một máy chủ hoặc quốc gia khác thường vượt qua được. Trên Android, hãy kiểm tra thêm xem hệ thống có đang đóng ứng dụng ở nền hay không."
      },
      {
        "id": "wifi_signin",
        "title": "Wi-Fi công cộng yêu cầu đăng nhập",
        "summary": "Quán cà phê, khách sạn, sân bay và tàu thường chặn mọi thứ cho đến khi bạn đăng nhập.",
        "body": "Những mạng này giữ lại toàn bộ lưu lượng cho đến khi bạn chấp nhận điều khoản trên trang đăng nhập, và VPN không thể kết nối trước đó. Hãy ngắt VPN, mở trình duyệt và tải một trang web thông thường bất kỳ — trang đăng nhập sẽ hiện ra. Hoàn tất đăng nhập, xác nhận duyệt web bình thường hoạt động, rồi mới kết nối VPN. Nếu không có trang nào hiện ra, hãy quên mạng đó trên thiết bị và kết nối lại từ đầu."
      },
      {
        "id": "network_blocks_vpn",
        "title": "Mạng của bạn chặn kết nối VPN",
        "summary": "Một số văn phòng, trường học, khách sạn và nhà mạng cố tình chặn lưu lượng VPN.",
        "body": "Nếu ứng dụng chạy được trên dữ liệu di động nhưng không chạy trên một mạng Wi-Fi nhất định, thì mạng đó đang cố tình chặn lưu lượng VPN. Đây là hạn chế do người quản lý mạng đặt ra, không phải lỗi của ứng dụng. Hãy thử máy chủ hoặc quốc gia khác — không phải tất cả đều bị chặn giống nhau — và thử lại sau khi đổi mạng. Trên các mạng được quản lý, như của công ty hay trường học, việc chặn thường được áp dụng tập trung và không thể vượt qua từ trong ứng dụng."
      },
      {
        "id": "android_battery",
        "title": "Android đang đóng ứng dụng ở nền",
        "summary": "Các tính năng tiết kiệm pin có thể tắt đường hầm khi màn hình tắt.",
        "body": "Android tích cực dừng các ứng dụng chạy nền để tiết kiệm pin, và điều đó có thể kết thúc phiên VPN mà bạn không hay biết. Hãy mở cài đặt thiết bị, tìm ứng dụng này trong mục Ứng dụng và đặt tùy chọn pin thành Không giới hạn (cách gọi khác nhau theo nhà sản xuất — Samsung, Xiaomi, Huawei và OnePlus đều dùng từ ngữ riêng). Cũng hãy chắc chắn ứng dụng không nằm trong danh sách 'ngủ' hay 'bị hạn chế'. Sau khi đổi, hãy kết nối lại; phiên kết nối sẽ trụ được khi màn hình tắt."
      },
      {
        "id": "ios_vpn_permission",
        "title": "iPhone yêu cầu cho phép cấu hình VPN",
        "summary": "iOS cần bạn cấp quyền một lần trước khi bất kỳ ứng dụng VPN nào có thể kết nối.",
        "body": "Ở lần kết nối đầu tiên, iOS sẽ hỏi để thêm một cấu hình VPN và có thể yêu cầu mật mã hoặc Face ID. Đây là lời nhắc tiêu chuẩn của iOS và ứng dụng không thể kết nối cho đến khi bạn cho phép. Nếu trước đó bạn đã từ chối, hãy vào Cài đặt, rồi Cài đặt chung, rồi VPN & Quản lý thiết bị, xóa mọi cấu hình cũ của ứng dụng này, rồi kết nối lại để nhận lời nhắc mới. Nếu có ứng dụng VPN khác đang cài, hãy đảm bảo nó đã ngắt kết nối — mỗi lần chỉ một VPN được hoạt động."
      },
      {
        "id": "device_clock",
        "title": "Ngày và giờ trên thiết bị bị sai",
        "summary": "Đồng hồ lệch quá vài phút sẽ phá vỡ quá trình bắt tay bảo mật.",
        "body": "Các kết nối bảo mật đối chiếu chứng chỉ với thời gian hiện tại, nên thiết bị có đồng hồ sai sẽ không kết nối được ngay cả trên một mạng hoàn hảo. Hãy mở cài đặt thiết bị, bật ngày và giờ tự động, rồi kết nối lại. Nguyên nhân này rất dễ bị bỏ qua, vì mọi thứ khác trên máy trông vẫn hoạt động bình thường."
      },
      {
        "id": "slow_speed",
        "title": "Kết nối chậm",
        "summary": "Tốc độ phụ thuộc chủ yếu vào khoảng cách tới máy chủ và mức độ bận của nó.",
        "body": "VPN luôn làm giảm một phần tốc độ, vì dữ liệu của bạn đi đường vòng xa hơn và được mã hóa trên đường truyền. Hãy chọn máy chủ gần bạn — một quốc gia lân cận hầu như luôn nhanh hơn quốc gia ở xa. Vuốt máy chủ sang trái và nhấn PING để xem nó phản hồi nhanh thế nào, và hãy ưu tiên con số thấp. Máy chủ miễn phí được nhiều người dùng chung và đông hơn vào giờ cao điểm; máy chủ cao cấp phục vụ ít người hơn. Hãy đo tốc độ khi tắt VPN nữa, để biết đường truyền của bạn thực sự đạt được bao nhiêu."
      },
      {
        "id": "streaming_blocked",
        "title": "Một dịch vụ phát trực tuyến không hoạt động",
        "summary": "Các nền tảng phát trực tuyến lớn chủ động phát hiện và chặn VPN.",
        "body": "Giấy phép buộc các dịch vụ phát trực tuyến phải phân phối nội dung theo từng quốc gia, nên họ đầu tư rất nhiều vào việc phát hiện và chặn lưu lượng VPN. Điều này ảnh hưởng tới mọi VPN chứ không riêng ứng dụng này, và một máy chủ hôm nay dùng được thì ngày mai có thể bị phát hiện. Thử máy chủ khác đôi khi có ích, nhưng không VPN nào có thể hứa hẹn truy cập được một dịch vụ phát trực tuyến cụ thể, và chúng tôi không thể bảo đảm điều đó."
      },
      {
        "id": "free_time_limit",
        "title": "Thời gian kết nối miễn phí đã hết",
        "summary": "Máy chủ miễn phí có một lượng thời gian kết nối mỗi ngày.",
        "body": "Máy chủ miễn phí đi kèm hạn mức thời gian kết nối hằng ngày và được đặt lại mỗi ngày. Khi hết, bạn có thể xem một video ngắn để gia hạn, với số lần giới hạn mỗi ngày. Đó là cách phiên bản miễn phí được chi trả, nên đây là thiết kế có chủ đích chứ không phải lỗi. Gói thuê bao sẽ bỏ hoàn toàn giới hạn thời gian, mở khóa mọi máy chủ và loại bỏ quảng cáo."
      },
      {
        "id": "subscription_help",
        "title": "Thuê bao, khôi phục và hoàn tiền",
        "summary": "Giao dịch mua do App Store và Google Play xử lý, không phải chúng tôi.",
        "body": "Nếu bạn đã đăng ký mà ứng dụng vẫn hiển thị bản miễn phí, hãy mở màn hình thuê bao và nhấn Khôi phục giao dịch mua, đồng thời bảo đảm bạn đang đăng nhập bằng tài khoản đã dùng để mua. Thuê bao tự động gia hạn và được hủy trong tài khoản cửa hàng của bạn — trên iPhone ở phần thuê bao của Tài khoản Apple, trên Android ở mục Thanh toán và gói thuê bao trong Play Store. Việc hoàn tiền do cửa hàng thực hiện, nên yêu cầu phải gửi tới Apple hoặc Google."
      }
    ]
  },
  "zh": {
    "lang": "zh",
    "dir": "ltr",
    "label": "中文",
    "heading": "帮助",
    "back": "← 全部主题",
    "stillStuck": "仍未解决？请发邮件至",
    "articles": [
      {
        "id": "cannot_connect",
        "title": "应用无法连接",
        "summary": "连接尝试失败或始终无法完成。",
        "body": "请先换一个服务器——单个服务器可能繁忙或临时故障，而更换服务器比其他任何方法都快。打开「服务器位置」，选择另一个国家，然后重新连接。如果所有服务器都不行，请关闭 Wi-Fi 改用移动数据（或反过来）：问题通常出在网络而不是应用。仍然不行？重启设备后再试一次。大多数连接失败都源于您所在的网络，这也是更换网络或服务器能解决其中绝大多数问题的原因。"
      },
      {
        "id": "keeps_dropping",
        "title": "连接不断断开",
        "summary": "连接成功后又被断开。",
        "body": "隧道刚建立就关闭，通常说明底层网络不稳定或在干扰 VPN 流量。请靠近路由器，或在 Wi-Fi 与移动数据之间切换，以排除信号问题。如果只在某一个网络中断开——办公室、学校、酒店——那么该网络很可能在过滤 VPN 流量，换一个服务器或国家往往就能通过。在 Android 上还请确认系统没有在后台关闭本应用。"
      },
      {
        "id": "wifi_signin",
        "title": "需要登录的公共 Wi-Fi",
        "summary": "咖啡馆、酒店、机场和列车常常在您登录前拦截一切流量。",
        "body": "这类网络会拦住全部流量，直到您在登录页面接受其条款，在此之前 VPN 无法连接。请断开 VPN，打开浏览器并访问任意普通网站——登录页面应会出现。完成登录，确认正常上网可用，然后再连接 VPN。如果没有任何页面出现，请在设备上忽略该网络后重新加入。"
      },
      {
        "id": "network_blocks_vpn",
        "title": "您的网络屏蔽了 VPN 连接",
        "summary": "一些办公室、学校、酒店和运营商会刻意屏蔽 VPN 流量。",
        "body": "如果应用在移动数据下正常，却在某个 Wi-Fi 下无法使用，说明该网络在刻意屏蔽 VPN 流量。这是网络管理者设置的限制，并非应用故障。请尝试其他服务器或国家——它们被屏蔽的方式并不相同——并在切换网络后再试。在公司或学校等受管网络中，屏蔽通常是集中实施的，无法从应用内绕过。"
      },
      {
        "id": "android_battery",
        "title": "Android 在后台关闭了应用",
        "summary": "省电功能可能在息屏时结束隧道。",
        "body": "Android 会积极停止后台应用以节省电量，这可能在您不知情时结束 VPN 会话。请打开设备设置，在「应用」中找到本应用，将其电池选项设为「无限制」（各厂商的叫法不同——三星、小米、华为和一加各有表述）。另请确认本应用不在任何「休眠」或「受限」名单中。更改之后重新连接，会话应能在息屏后继续保持。"
      },
      {
        "id": "ios_vpn_permission",
        "title": "iPhone 请求允许 VPN 配置",
        "summary": "任何 VPN 应用连接前，iOS 都需要您授权一次。",
        "body": "首次连接时，iOS 会请求添加 VPN 配置，并可能要求输入密码或使用面容 ID。这是 iOS 的标准提示，在您允许之前应用无法连接。如果您此前拒绝过，请前往「设置」—「通用」—「VPN 与设备管理」，删除本应用的旧配置，然后重新连接以再次获得提示。如果还安装了其他 VPN 应用，请确认它已断开——同一时间只能有一个 VPN 处于活动状态。"
      },
      {
        "id": "device_clock",
        "title": "设备的日期和时间不正确",
        "summary": "时钟偏差超过几分钟就会破坏安全握手。",
        "body": "安全连接会按当前时间校验证书，因此时钟错误的设备即使在完好的网络下也会连接失败。请打开设备设置，开启自动设置日期与时间，然后重新连接。这一点很容易被忽略，因为设备上的其他功能看起来一切正常。"
      },
      {
        "id": "slow_speed",
        "title": "连接速度慢",
        "summary": "速度主要取决于与服务器的距离及其繁忙程度。",
        "body": "VPN 总会损失一些速度，因为流量要走更长的路径并在途中加密。请选择离您较近的服务器——邻近国家几乎总比遥远国家更快。向左滑动服务器并点按 PING，查看其响应速度，数值越低越好。免费服务器由大量用户共享，高峰时段更为拥挤；高级服务器承载的用户较少。也请在关闭 VPN 的情况下测一次速度，以了解您的线路实际能达到多少。"
      },
      {
        "id": "streaming_blocked",
        "title": "某个流媒体服务无法使用",
        "summary": "大型流媒体平台会主动检测并屏蔽 VPN。",
        "body": "流媒体服务受授权条款约束，必须按国家分发内容，因此投入大量资源检测并屏蔽 VPN 流量。这影响所有 VPN，并非仅限本应用，今天可用的服务器明天可能就被识别。换一个服务器有时会有帮助，但没有任何 VPN 能承诺访问某个特定的流媒体服务，我们也无法保证。"
      },
      {
        "id": "free_time_limit",
        "title": "免费连接时长已用完",
        "summary": "免费服务器每天包含一定的连接时长。",
        "body": "免费服务器设有每日连接时长额度，每天重置。用完之后，您可以观看一段短视频来延长，每天次数有限。免费版正是以此方式获得收入，所以这是既定设计而非故障。订阅可彻底取消时长限制、解锁全部服务器并去除广告。"
      },
      {
        "id": "subscription_help",
        "title": "订阅、恢复购买与退款",
        "summary": "购买由 App Store 和 Google Play 处理，而非由我们处理。",
        "body": "如果您已订阅但应用仍显示免费版，请打开订阅页面并点按「恢复购买」，并确认您登录的是购买时所用的账户。订阅会自动续期，并在您的商店账户中取消——iPhone 上在 Apple 账户的订阅中，Android 上在 Play 商店的「付款和订阅」中。退款由商店办理，因此请向 Apple 或 Google 提出申请。"
      }
    ]
  }
};

export const HELP_LANGS = Object.keys(HELP_LOCALES);

export function getLocale(lang: string): HelpLocale | undefined {
  return HELP_LOCALES[lang];
}

export function getArticle(lang: string, id: string): HelpArticle | undefined {
  return HELP_LOCALES[lang]?.articles.find((a) => a.id === id);
}
