// GENERATED by knowledge-base/generate.py in the app repo — do not edit here.
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import {
  HELP_LANGS,
  SUPPORT_EMAIL,
  getArticle,
  getLocale,
} from "../../help-content";

export function generateStaticParams() {
  return HELP_LANGS.flatMap((lang) =>
    (getLocale(lang)?.articles ?? []).map((article) => ({
      lang,
      slug: article.id,
    })),
  );
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lang: string; slug: string }>;
}): Promise<Metadata> {
  const { lang, slug } = await params;
  const article = getArticle(lang, slug);
  if (!article) return {};
  return {
    title: `${article.title} - Saudi Arabia VPN`,
    description: article.summary,
    alternates: {
      canonical: `/help/${lang}/${slug}`,
      languages: Object.fromEntries(
        HELP_LANGS.map((l) => [l, `/help/${l}/${slug}`]),
      ),
    },
  };
}

export default async function HelpArticle({
  params,
}: {
  params: Promise<{ lang: string; slug: string }>;
}) {
  const { lang, slug } = await params;
  const locale = getLocale(lang);
  const article = getArticle(lang, slug);
  if (!locale || !article) notFound();

  return (
    <div className="bg-sand-light min-h-screen py-20" dir={locale.dir}>
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-white rounded-2xl shadow-lg p-8 md:p-12">
          <Link
            href={`/help/${lang}`}
            className="mb-6 inline-block text-sm text-slate-dark/60 hover:text-slate-dark"
          >
            {locale.back}
          </Link>

          <h1 className="text-3xl md:text-4xl font-bold text-slate-dark mb-3">
            {article.title}
          </h1>
          <p className="text-lg text-slate-dark/60 mb-8">{article.summary}</p>

          <div className="prose prose-lg max-w-none text-slate-dark/80">
            <p>{article.body}</p>
          </div>

          <p className="mt-10 border-t border-sand-dark/40 pt-6 text-slate-dark/70">
            {locale.stillStuck}{" "}
            <a className="text-app-teal underline" href={`mailto:${SUPPORT_EMAIL}`}>
              {SUPPORT_EMAIL}
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}
