// GENERATED by knowledge-base/generate.py in the app repo — do not edit here.
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { HELP_LANGS, SUPPORT_EMAIL, getLocale } from "../help-content";

export function generateStaticParams() {
  return HELP_LANGS.map((lang) => ({ lang }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lang: string }>;
}): Promise<Metadata> {
  const { lang } = await params;
  const locale = getLocale(lang);
  if (!locale) return {};
  return {
    title: `${locale.heading} - Saudi Arabia VPN`,
    description: locale.articles.map((a) => a.title).join(" . "),
    alternates: {
      canonical: `/help/${lang}`,
      languages: Object.fromEntries(HELP_LANGS.map((l) => [l, `/help/${l}`])),
    },
  };
}

export default async function HelpIndex({
  params,
}: {
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  const locale = getLocale(lang);
  if (!locale) notFound();

  return (
    <div className="bg-sand-light min-h-screen py-20" dir={locale.dir}>
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-white rounded-2xl shadow-lg p-8 md:p-12">
          <h1 className="text-4xl font-bold text-slate-dark mb-8">
            {locale.heading}
          </h1>

          <ul className="space-y-3">
            {locale.articles.map((article) => (
              <li key={article.id}>
                <Link
                  href={`/help/${lang}/${article.id}`}
                  className="block rounded-xl border border-sand-dark/40 bg-sand-light/60 p-5 transition hover:border-app-green hover:bg-sand-light"
                >
                  <span className="block font-semibold text-slate-dark">
                    {article.title}
                  </span>
                  <span className="mt-1 block text-slate-dark/70">
                    {article.summary}
                  </span>
                </Link>
              </li>
            ))}
          </ul>

          <p className="mt-10 border-t border-sand-dark/40 pt-6 text-slate-dark/70">
            {locale.stillStuck}{" "}
            <a className="text-app-teal underline" href={`mailto:${SUPPORT_EMAIL}`}>
              {SUPPORT_EMAIL}
            </a>
          </p>

          <p className="mt-6 flex flex-wrap gap-x-4 gap-y-2 text-sm text-slate-dark/60">
            {HELP_LANGS.map((other) => (
              <Link key={other} href={`/help/${other}`} className="hover:text-slate-dark">
                {getLocale(other)?.label}
              </Link>
            ))}
          </p>
        </div>
      </div>
    </div>
  );
}
